# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='allow_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='allow_comments',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
